version: '2'
services:
  db:
    image: postgres:9.3.13
    ports:
      - "5432:5432"

  ironman:
    build: ../ironman
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    environment:
      - RAILS_ENV=development
      - DATABASE_URL=postgres://postgres@db:5432
    stdin_open: true
    tty: true
    ports:
      - "3000:3000"
    links:
      - db
    volumes:
      - ../ironman:/myapp
